FROM golang:1.18-alpine

# HINT:: this Dockerfile only for development

# this file for the development only
RUN mkdir /app
COPY ./app /app
WORKDIR /app

RUN chmod +x /app/start.sh

RUN apk add vim bash
RUN go install github.com/cosmtrek/air@latest

# In this case air command for hot reload go apps on file changes
ENTRYPOINT air

EXPOSE 8080
