FROM golang:1.18-alpine AS builder

# this file for the development only
RUN mkdir /app
COPY . /app
WORKDIR /app

RUN go get github.com/githubnemo/CompileDaemon

FROM alpine:latest AS runner

WORKDIR /app
COPY --from=builder /app .
RUN chmod +x entrypoint.sh

EXPOSE 8080
ENTRYPOINT ["entrypoint.sh"]
